###
GET http://localhost:8090/api/products?limit=10 

###
POST http://localhost:8090/api/products
Content-Type: application/json

{
    "productName": "Shoes",
      "categoryName": "Clothes",
      "categpryId": 3,
      "price": "$3.99",
      "isTrending": true
}
###
DELETE http://localhost:8090/api/products/1

###
PUT http://localhost:8090/api/products
Content-Type: application/json

{ 
     "productId": "e5d946ee-6468-4211-b9f5-00eb711d5fbf",
     "productName": "MicroWave",
      "categoryName": "Home",
      "categpryId": 2,
      "price": "$6.99",
      "isTrending": true,
      "isLiked" : true
}