###
GET http://localhost:8090/api/user?limit=10

###
GET http://localhost:8090/api/user/1


###
POST http://localhost:8090/api/user
Content-Type: application/json

{
    "first_name" : "Taami",
    "last_name" : "Nado",
    "age" : 23,
    "user_name" : "Test",
    "birth_date" : "1990-02-01"

} 

### 
PUT http://localhost:8090/api/user/1
Content-Type: application/json

{
    "first_name" : "Ganzooooo",
    "last_name" : "Ganzorig",
    "age" : 18,
    "user_name" : "testets",
    "birth_date" : "2009-12-01",


}

###
DELETE http://localhost:8090/api/user/1
