###
GET http://localhost:8090/api/user

###
POST http://localhost:8090/api/user
Content-Type: application/json

{
    "userName" : "Taami",
    "firstName" : "Nado",
    "userType" : "Admin",
    "lastName" : "Test",
    "password" : "123"

} 

### 
PUT http://localhost:8090/api/user/b57fb59c-d11d-4c94-809c-e51665e61cd8
Content-Type: application/json

{
    "userName" : "Ganzooooo",
    "firstName" : "Ganzorig",
    "userType" : "User",
    "lastName" : "Bat-Erdene",
    "password" : "1231"

}

###
DELETE http://localhost:8090/api/user/3e65e6fe-e962-4a50-a4be-db1d59f7c05b
